name: Build and test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build-essential
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install librairies
        shell: bash
        run: |
          sudo apt-get install -y libgtk-3-dev libcriterion-dev

      - name: Build project
        run: |
          make VERBOSE=1 XCFLAGS=-Werror test
